# Site settings
title: 橘子皮
SEOTitle: JuuciePのBlog
header-img: img/home-bg-bluestars.jpg
email: QQ：1354961639
description: "一个简单的个人博客站"
keyword: "JuuiceP,Juuice,橘子皮"
url: "https://JuuiceP.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/JuuiceP/JuuiceP.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一个简单的个人博客站"
sidebar-avatar: /img/about_juuicep.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:       henry-jiang-78
#github_username:      globien
#facebook_username:    henry.h.jiang.5
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f63dbe1e1aab4240cb49                           #生成的clientID
  clientSecret: 1ade84181ee2c501b589a3762153dd594c18f333    #生成的clientSecret
  repo:  JuuiceP.github.io    #仓库名称
  owner: JuuiceP    #github用户名
  admin: JuuiceP
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接，请尽量不要删除
friends: [
    {
        title: "Baidu",
        href: "https://baidu.com"
    },{
        title: "BiLiBiLi",
        href: "https://bilibili.com"
    }
]
